%w[xot reight]
  .map  {|s| File.expand_path "../../#{s}/lib", __dir__}
  .each {|s| $:.unshift s if !$:.include?(s) && File.directory?(s)}

require 'json'
require 'erb'
require 'xot/rake/util'
require 'reight/extension'

include Xot::Rake


NAME = 'reight'

ROOT_DIR   = File.expand_path '../..', __dir__
BUNDLE_DIR = 'vendor/bundle'
DATA_DIR   = '.data'
OUT_DIR    = 'output'

GEMS     = Dir.glob("#{ROOT_DIR}/*/*.gemspec").map {File.basename File.dirname _1}
GEM_SRCS = GEMS.map {Dir.glob "#{ROOT_DIR}/#{_1}/**/*.{h,hpp,c,cpp,m,mm,rb}"}.flatten

OUT_WASM   = "#{OUT_DIR}/ruby.wasm"
OUT_JS     = "#{OUT_DIR}/#{NAME}.js"
OUT_DATA   = "#{OUT_DIR}/#{NAME}.data"
OUT_LIB_JS = "#{OUT_DIR}/#{NAME}lib.js"
OUT_FILES  = [OUT_WASM, OUT_JS, OUT_DATA, OUT_LIB_JS]


task :default => :build

task :clean => 'test:clean' do
  Dir.chdir ROOT_DIR do
    sh %( rake clean )
  end
  sh %( rm -rf build rubies #{BUNDLE_DIR} #{DATA_DIR} #{OUT_DIR} )
end

task :clobber => :clean do
  Dir.chdir ROOT_DIR do
    sh %( rake clobber )
  end
end

task :build => OUT_DATA

task :publish => :build do
  File.write "#{OUT_DIR}/package.json", JSON.pretty_generate(
    name:        'reight-wasm',
    version:     Reight::Extension.version,
    description: 'Reight game engine WASM build',
    files:       OUT_FILES.map {File.basename _1},
    repository:  {type: 'git', url: 'git+https://github.com/xord/reight.git'},
    license:     'MIT'
  )
  sh %( cd #{OUT_DIR} && npm publish --provenance )
end

file OUT_DATA => OUT_WASM do
  emroot   = `em-config EMSCRIPTEN_ROOT`.strip
  raise 'emscripten not found' if emroot.empty?

  packager = "#{emroot}/tools/file_packager"
  opts     = [
    "--preload '#{DATA_DIR}@/'",
    "--export-name=globalThis.__ruby_module"
  ]
  loader   = `#{packager} #{OUT_DATA} #{opts.join ' '}`
  raise 'file_packager failed' if !$?.success? || loader.empty?

  File.write OUT_LIB_JS, "export function loadReightLib() {#{loader}};"
end

file OUT_WASM => [BUNDLE_DIR, OUT_DIR] + GEM_SRCS do
  sh %( rm -rf #{DATA_DIR} )

  backups = {}
  begin
    GEMS.each do |gem|
      path = "#{ROOT_DIR}/#{gem}/#{gem}.gemspec"
      filter_file path do |s|
        backups[path] = s
        s.sub(/^(.*\.\s*extensions.*)$/) {$1.sub 'Rakefile', "ext/#{gem}/extconf.rb"}
      end
    end

    ldflags = %W[
      -sASYNCIFY_STACK_SIZE=#{1024 * 1024 * 4}
      -sNO_DISABLE_EXCEPTION_CATCHING
      -sFORCE_FILESYSTEM
      -sUSE_SDL=2
      -sUSE_SDL_TTF=2
      -sALLOW_MEMORY_GROWTH=1
      -sINITIAL_MEMORY=#{1024 * 1024 * 64}
      -sEXPORTED_RUNTIME_METHODS=ccall,cwrap,UTF8ToString,stringToUTF8,FS
      -sASSERTIONS=1
      -fexceptions
    ].reject {_1 =~ /^\s*#/}
    envs    = "RUBY_WASM_EMCC_LDFLAGS=' #{ldflags.join ' '}'"
    sysopts = '--log-level debug'
    opts    = "--target wasm32-unknown-emscripten --dest_dir #{DATA_DIR} --remake -o #{OUT_JS}"
    sh %( #{envs} bundle exec rbwasm #{sysopts} build #{opts} )
  ensure
    backups.each {|path, s| File.write path, s}
  end

  roots = Dir.glob('rubies/ruby-*-wasm*-*-emscripten-full-*')
    .select {File.directory? _1}
  raise "expected 1 root, got #{roots.size}" if roots.size != 1
  sh %( cp -f #{roots.first}/usr/local/bin/ruby.wasm #{OUT_WASM} )
end

file BUNDLE_DIR do
  sh %( bundle install )
end

directory OUT_DIR


namespace :test do
  template_dir = 'template'
  test_dir     = 'test'
  main         = "#{test_dir}/test.rb"
  erbs         = {
    "#{test_dir}/index.html" => "#{template_dir}/index.html.erb"
  }
  wasm_files   = OUT_FILES.each.with_object({}) {|out, hash|
    hash["#{test_dir}/#{File.basename out}"] = out
  }

  task :clean do
    sh %( rm -rf #{test_dir} )
  end

  task :serve => [main] + erbs.keys + wasm_files.keys do
    require 'webrick'
    WEBrick::HTTPServer.new(Port: 8080, DocumentRoot: test_dir).start
  end

  erbs.each do |out, erb|
    base    = '.'
    main_rb = File.basename main
    task out => [test_dir, erb] do
      File.write out, ERB.new(File.read erb).result(binding)
    end
  end

  wasm_files.each do |to, from|
    task to => [test_dir, from] do
      File.symlink "../#{from}", to unless File.symlink? to
    end
  end

  file main => test_dir do
    File.write main, <<~'END'
    require 'rubysketch'
    using RubySketch

    setup do
      size 640, 480
      gravity 0, 1000
      @grounds = [
        createSprite(0, height - 30, width, 30),
        createSprite(0,          0, 10, height),
        createSprite(width - 10, 0, 10, height)
      ]
      @sprites = []
    end

    draw do
      background 20
      fill 100
      sprite @grounds
      fill 0, 200, 100
      sprite @sprites
      fill 255
      textSize 24
      textAlign RIGHT
      text "#{frameRate.round} FPS", width - 100, 30
    end

    mousePressed do
      s = createSprite mouseX, mouseY, 30, 30
      s.dynamic = true
      @sprites << s
    end
    END
  end

  directory test_dir
end
