%w[xot reight]
  .map  {|s| File.expand_path "../../#{s}/lib", __dir__}
  .each {|s| $:.unshift s if !$:.include?(s) && File.directory?(s)}

require 'json'
require 'erb'
require 'xot/rake/util'
require 'reight/extension'

include Xot::Rake


NAME = 'reight'

ROOT_DIR   = File.expand_path '../..', __dir__
BUNDLE_DIR = 'vendor/bundle'
DATA_DIR   = '.data'
OUT_DIR    = 'output'

GEMS     = Dir.glob("#{ROOT_DIR}/*/*.gemspec").map {File.basename File.dirname _1}
GEM_SRCS = GEMS.flat_map {|gem|
  Dir.glob "#{ROOT_DIR}/#{gem}/{include,src,ext,lib}/**/*.{h,hpp,c,cpp,m,mm,rb}"
}

OUT_WASM   = "#{OUT_DIR}/ruby.wasm"
OUT_JS     = "#{OUT_DIR}/#{NAME}.js"
OUT_DATA   = "#{OUT_DIR}/#{NAME}.data"
OUT_LIB_JS = "#{OUT_DIR}/#{NAME}lib.js"
OUT_FILES  = [OUT_WASM, OUT_JS, OUT_DATA, OUT_LIB_JS]


task :default => :build

task :clean => 'test:clean' do
  Dir.chdir ROOT_DIR do
    sh %( rake clean )
  end
  sh %( rm -rf build rubies #{DATA_DIR} #{OUT_DIR} )
end

task :clobber => :clean do
  Dir.chdir ROOT_DIR do
    sh %( rake clobber )
  end
  sh %( rm -rf #{BUNDLE_DIR} )
end

task :build => OUT_DATA

task :publish => :build do
  File.write "#{OUT_DIR}/package.json", JSON.pretty_generate(
    name:        'reight-wasm',
    version:     Reight::Extension.version,
    description: 'Reight game engine WASM build',
    files:       OUT_FILES.map {File.basename _1},
    repository:  {type: 'git', url: 'git+https://github.com/xord/reight.git'},
    license:     'MIT'
  )
  sh %( cd #{OUT_DIR} && npm publish --provenance )
end

file OUT_DATA => OUT_WASM do
  emroot   = `em-config EMSCRIPTEN_ROOT`.strip
  raise 'emscripten not found' if emroot.empty?

  packager = "#{emroot}/tools/file_packager"
  opts     = [
    "--preload '#{DATA_DIR}@/'",
    "--export-name=globalThis.__ruby_module"
  ]
  loader   = `#{packager} #{OUT_DATA} #{opts.join ' '}`
  raise 'file_packager failed' if !$?.success? || loader.empty?

  File.write OUT_LIB_JS, "export function loadReightLib() {#{loader}};"
end

file OUT_WASM => [BUNDLE_DIR, OUT_DIR] + GEM_SRCS do
  sh %( rm -rf #{DATA_DIR} )

  backups = {}
  begin
    GEMS.each do |gem|
      path = "#{ROOT_DIR}/#{gem}/#{gem}.gemspec"
      filter_file path do |s|
        backups[path] = s
        s.sub(/^(.*\.\s*extensions.*)$/) {$1.sub 'Rakefile', "ext/#{gem}/extconf.rb"}
      end
    end

    ldflags = %W[
      -sALLOW_MEMORY_GROWTH=1
      -sINITIAL_MEMORY=#{1024 * 1024 * 64}
      -sASYNCIFY_STACK_SIZE=#{1024 * 1024 * 4}
      -fexceptions
      -sNO_DISABLE_EXCEPTION_CATCHING
      -sFORCE_FILESYSTEM
      -sUSE_SDL=2
      -sUSE_SDL_TTF=2
      -sEXPORTED_RUNTIME_METHODS=ccall,cwrap,UTF8ToString,stringToUTF8,FS
    ].reject {_1 =~ /^\s*#/}.join ' '
    envs    = [
      "RUBY_WASM_EMCC_LDFLAGS='#{ldflags}'",
      # avoid host's libyaml (e.g. Homebrew) being picked up by psych extconf
      "PKG_CONFIG_LIBDIR=''"
    ].join ' '
    opts    = %W[
      --target wasm32-unknown-emscripten
      --dest_dir #{DATA_DIR}
      --remake
      -o #{OUT_JS}
    ].join ' '
    sh %( #{envs} bundle exec rbwasm build #{opts} )
  ensure
    backups.each {|path, s| File.write path, s}
  end

  roots = Dir.glob('rubies/ruby-*-wasm*-*-emscripten-*-*')
    .select {File.directory? _1}
  raise "expected 1 root, got #{roots.size}" if roots.size != 1
  sh %( cp -f #{roots.first}/usr/local/bin/ruby.wasm #{OUT_WASM} )
end

file BUNDLE_DIR do
  sh %( bundle install )
end

directory OUT_DIR


namespace :test do
  to_path_map = -> paths, &block {
    paths
      .reject {_1.end_with? '~'}
      .reject {File.directory? _1}
      .map {[_1, block.call(_1)]}
      .to_h
  }

  cdn_url        = "https://cdn.jsdelivr.net/npm/reight-wasm@#{Reight::Extension.version}"
  test_dir       = 'test'
  template_dir   = 'template'
  template_files = to_path_map[Dir.glob "#{template_dir}/**/*"] {
    _1.sub(/^#{template_dir}/, test_dir).sub(/\.erb$/, '')
  }
  wasm_files     = to_path_map[OUT_FILES] {
    "#{test_dir}/#{File.basename _1}"
  }
  assets         = to_path_map[["../../rubysketch/examples/physics.rb"]] {
    "#{test_dir}/#{File.basename _1}"
  }

  task :clean do
    sh %( rm -rf #{test_dir} )
  end

  task :serve => template_files.values + wasm_files.values + assets.values do
    require 'webrick'
    WEBrick::HTTPServer.new(Port: 8080, DocumentRoot: test_dir).start
  end

  task :deploy => template_files.values + assets.values do
    wasm_files.values.each {File.unlink _1 if File.symlink? _1}
    Dir.glob("#{test_dir}/**/*").each {puts _1}
    print "Deploy? [y/n]: "
    next unless $stdin.gets =~ /^(y|yes)$/i
    sh %( npx wrangler pages deploy #{test_dir} --branch master )
  end

  template_files.each do |from, to|
    paths = assets.values.map {_1.sub /^#{test_dir}/, ''}

    file to => [test_dir, from] do
      if from.end_with? '.erb'
        File.write to, ERB.new(File.read from).result_with_hash(
          wasm_url_base: cdn_url, assets: paths, main: paths.first)
      else
        sh %( cp #{from} #{to} )
      end
    end
  end

  wasm_files.each do |from, to|
    file to => [OUT_DATA, test_dir, from] do
      File.symlink "../#{from}", to unless File.symlink? to
    end
  end

  assets.each do |from, to|
    file to => [test_dir, from] do
      sh %( cp #{from} #{to} )
      filter_file to do |s|
        words = %w[map expand_path lib dir each unshift include directory]
        s.sub(/^.*\%w\[.*\].*#{words.join '.*'}.*?(require)/m) {$1}
      end
    end
  end

  directory test_dir
end
